FROM --platform=amd64 golang:1.26.4

WORKDIR /app

ENV GOPRIVATE=github.com/meetgeekai/*

# Configures Git to use specific credentials
ARG AUTH_USER
ARG AUTH_TOKEN
RUN git config --global url."https://${AUTH_USER}:${AUTH_TOKEN}@github.com".insteadOf "https://github.com" \
    && GOOS=linux GOARCH=amd64 go install github.com/air-verse/air@latest

CMD ["/go/bin/air", "-c", ".air.toml"]
