// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation_template_queries.sql

package models

import (
	"context"
	"strings"
)

const getConversationTemplateNames = `-- name: GetConversationTemplateNames :many
SELECT
    ct.id,
    ct.name
FROM
    conversation_templates ct
WHERE
    ct.id IN (/*SLICE:ids*/?)
    AND ct.user_id = ?
`

type GetConversationTemplateNamesParams struct {
	Ids    []uint32 `json:"ids"`
	UserID uint32   `json:"user_id"`
}

type GetConversationTemplateNamesRow struct {
	ID   uint32 `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetConversationTemplateNames(ctx context.Context, arg GetConversationTemplateNamesParams) ([]GetConversationTemplateNamesRow, error) {
	query := getConversationTemplateNames
	var queryParams []interface{}
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.UserID)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConversationTemplateNamesRow
	for rows.Next() {
		var i GetConversationTemplateNamesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
