// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integration_queries.sql

package models

import (
	"context"
)

const getConnectedCalendarVendors = `-- name: GetConnectedCalendarVendors :many
SELECT DISTINCT
    i.vendor
FROM
    integrations i
WHERE
    i.user_uuid = ?
    AND i.type = 'Calendar'
    AND i.active = 1
    AND i.error_code IS NULL
    AND i.vendor IN ('google', 'microsoft')
`

func (q *Queries) GetConnectedCalendarVendors(ctx context.Context, userUuid string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getConnectedCalendarVendors, userUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var vendor string
		if err := rows.Scan(&vendor); err != nil {
			return nil, err
		}
		items = append(items, vendor)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
