// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package models

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type ConversationTemplatesLanguageCode string

const (
	ConversationTemplatesLanguageCodeAfZA      ConversationTemplatesLanguageCode = "af-ZA"
	ConversationTemplatesLanguageCodeSqAL      ConversationTemplatesLanguageCode = "sq-AL"
	ConversationTemplatesLanguageCodeAmET      ConversationTemplatesLanguageCode = "am-ET"
	ConversationTemplatesLanguageCodeArDZ      ConversationTemplatesLanguageCode = "ar-DZ"
	ConversationTemplatesLanguageCodeArBH      ConversationTemplatesLanguageCode = "ar-BH"
	ConversationTemplatesLanguageCodeArEG      ConversationTemplatesLanguageCode = "ar-EG"
	ConversationTemplatesLanguageCodeArIQ      ConversationTemplatesLanguageCode = "ar-IQ"
	ConversationTemplatesLanguageCodeArIL      ConversationTemplatesLanguageCode = "ar-IL"
	ConversationTemplatesLanguageCodeArJO      ConversationTemplatesLanguageCode = "ar-JO"
	ConversationTemplatesLanguageCodeArKW      ConversationTemplatesLanguageCode = "ar-KW"
	ConversationTemplatesLanguageCodeArLB      ConversationTemplatesLanguageCode = "ar-LB"
	ConversationTemplatesLanguageCodeArLY      ConversationTemplatesLanguageCode = "ar-LY"
	ConversationTemplatesLanguageCodeArMA      ConversationTemplatesLanguageCode = "ar-MA"
	ConversationTemplatesLanguageCodeArOM      ConversationTemplatesLanguageCode = "ar-OM"
	ConversationTemplatesLanguageCodeArQA      ConversationTemplatesLanguageCode = "ar-QA"
	ConversationTemplatesLanguageCodeArSA      ConversationTemplatesLanguageCode = "ar-SA"
	ConversationTemplatesLanguageCodeArSY      ConversationTemplatesLanguageCode = "ar-SY"
	ConversationTemplatesLanguageCodeArPS      ConversationTemplatesLanguageCode = "ar-PS"
	ConversationTemplatesLanguageCodeArTN      ConversationTemplatesLanguageCode = "ar-TN"
	ConversationTemplatesLanguageCodeArAE      ConversationTemplatesLanguageCode = "ar-AE"
	ConversationTemplatesLanguageCodeArYE      ConversationTemplatesLanguageCode = "ar-YE"
	ConversationTemplatesLanguageCodeHyAM      ConversationTemplatesLanguageCode = "hy-AM"
	ConversationTemplatesLanguageCodeAzAZ      ConversationTemplatesLanguageCode = "az-AZ"
	ConversationTemplatesLanguageCodeEuES      ConversationTemplatesLanguageCode = "eu-ES"
	ConversationTemplatesLanguageCodeBnBD      ConversationTemplatesLanguageCode = "bn-BD"
	ConversationTemplatesLanguageCodeBnIN      ConversationTemplatesLanguageCode = "bn-IN"
	ConversationTemplatesLanguageCodeBsBA      ConversationTemplatesLanguageCode = "bs-BA"
	ConversationTemplatesLanguageCodeBgBG      ConversationTemplatesLanguageCode = "bg-BG"
	ConversationTemplatesLanguageCodeMyMM      ConversationTemplatesLanguageCode = "my-MM"
	ConversationTemplatesLanguageCodeCaES      ConversationTemplatesLanguageCode = "ca-ES"
	ConversationTemplatesLanguageCodeZhHK      ConversationTemplatesLanguageCode = "zh-HK"
	ConversationTemplatesLanguageCodeYueHantHK ConversationTemplatesLanguageCode = "yue-Hant-HK"
	ConversationTemplatesLanguageCodeZhCN      ConversationTemplatesLanguageCode = "zh-CN"
	ConversationTemplatesLanguageCodeZh        ConversationTemplatesLanguageCode = "zh"
	ConversationTemplatesLanguageCodeCmnHansCN ConversationTemplatesLanguageCode = "cmn-Hans-CN"
	ConversationTemplatesLanguageCodeZhTW      ConversationTemplatesLanguageCode = "zh-TW"
	ConversationTemplatesLanguageCodeCmnHantTW ConversationTemplatesLanguageCode = "cmn-Hant-TW"
	ConversationTemplatesLanguageCodeHrHR      ConversationTemplatesLanguageCode = "hr-HR"
	ConversationTemplatesLanguageCodeCsCZ      ConversationTemplatesLanguageCode = "cs-CZ"
	ConversationTemplatesLanguageCodeDaDK      ConversationTemplatesLanguageCode = "da-DK"
	ConversationTemplatesLanguageCodeNlBE      ConversationTemplatesLanguageCode = "nl-BE"
	ConversationTemplatesLanguageCodeNlNL      ConversationTemplatesLanguageCode = "nl-NL"
	ConversationTemplatesLanguageCodeEnAU      ConversationTemplatesLanguageCode = "en-AU"
	ConversationTemplatesLanguageCodeEnCA      ConversationTemplatesLanguageCode = "en-CA"
	ConversationTemplatesLanguageCodeEnGH      ConversationTemplatesLanguageCode = "en-GH"
	ConversationTemplatesLanguageCodeEnHK      ConversationTemplatesLanguageCode = "en-HK"
	ConversationTemplatesLanguageCodeEnIN      ConversationTemplatesLanguageCode = "en-IN"
	ConversationTemplatesLanguageCodeEnIE      ConversationTemplatesLanguageCode = "en-IE"
	ConversationTemplatesLanguageCodeEnKE      ConversationTemplatesLanguageCode = "en-KE"
	ConversationTemplatesLanguageCodeEnNZ      ConversationTemplatesLanguageCode = "en-NZ"
	ConversationTemplatesLanguageCodeEnNG      ConversationTemplatesLanguageCode = "en-NG"
	ConversationTemplatesLanguageCodeEnPK      ConversationTemplatesLanguageCode = "en-PK"
	ConversationTemplatesLanguageCodeEnPH      ConversationTemplatesLanguageCode = "en-PH"
	ConversationTemplatesLanguageCodeEnSG      ConversationTemplatesLanguageCode = "en-SG"
	ConversationTemplatesLanguageCodeEnZA      ConversationTemplatesLanguageCode = "en-ZA"
	ConversationTemplatesLanguageCodeEnTZ      ConversationTemplatesLanguageCode = "en-TZ"
	ConversationTemplatesLanguageCodeEnGB      ConversationTemplatesLanguageCode = "en-GB"
	ConversationTemplatesLanguageCodeEnUS      ConversationTemplatesLanguageCode = "en-US"
	ConversationTemplatesLanguageCodeEtEE      ConversationTemplatesLanguageCode = "et-EE"
	ConversationTemplatesLanguageCodeFilPH     ConversationTemplatesLanguageCode = "fil-PH"
	ConversationTemplatesLanguageCodeFiFI      ConversationTemplatesLanguageCode = "fi-FI"
	ConversationTemplatesLanguageCodeFrBE      ConversationTemplatesLanguageCode = "fr-BE"
	ConversationTemplatesLanguageCodeFrCA      ConversationTemplatesLanguageCode = "fr-CA"
	ConversationTemplatesLanguageCodeFrFR      ConversationTemplatesLanguageCode = "fr-FR"
	ConversationTemplatesLanguageCodeFrCH      ConversationTemplatesLanguageCode = "fr-CH"
	ConversationTemplatesLanguageCodeGlES      ConversationTemplatesLanguageCode = "gl-ES"
	ConversationTemplatesLanguageCodeKaGE      ConversationTemplatesLanguageCode = "ka-GE"
	ConversationTemplatesLanguageCodeDeAT      ConversationTemplatesLanguageCode = "de-AT"
	ConversationTemplatesLanguageCodeDeDE      ConversationTemplatesLanguageCode = "de-DE"
	ConversationTemplatesLanguageCodeDeCH      ConversationTemplatesLanguageCode = "de-CH"
	ConversationTemplatesLanguageCodeElGR      ConversationTemplatesLanguageCode = "el-GR"
	ConversationTemplatesLanguageCodeGuIN      ConversationTemplatesLanguageCode = "gu-IN"
	ConversationTemplatesLanguageCodeHeIL      ConversationTemplatesLanguageCode = "he-IL"
	ConversationTemplatesLanguageCodeIwIL      ConversationTemplatesLanguageCode = "iw-IL"
	ConversationTemplatesLanguageCodeHiIN      ConversationTemplatesLanguageCode = "hi-IN"
	ConversationTemplatesLanguageCodeHuHU      ConversationTemplatesLanguageCode = "hu-HU"
	ConversationTemplatesLanguageCodeIsIS      ConversationTemplatesLanguageCode = "is-IS"
	ConversationTemplatesLanguageCodeIDID      ConversationTemplatesLanguageCode = "id-ID"
	ConversationTemplatesLanguageCodeGaIE      ConversationTemplatesLanguageCode = "ga-IE"
	ConversationTemplatesLanguageCodeItIT      ConversationTemplatesLanguageCode = "it-IT"
	ConversationTemplatesLanguageCodeItCH      ConversationTemplatesLanguageCode = "it-CH"
	ConversationTemplatesLanguageCodeJaJP      ConversationTemplatesLanguageCode = "ja-JP"
	ConversationTemplatesLanguageCodeJvID      ConversationTemplatesLanguageCode = "jv-ID"
	ConversationTemplatesLanguageCodeKnIN      ConversationTemplatesLanguageCode = "kn-IN"
	ConversationTemplatesLanguageCodeKkKZ      ConversationTemplatesLanguageCode = "kk-KZ"
	ConversationTemplatesLanguageCodeKmKH      ConversationTemplatesLanguageCode = "km-KH"
	ConversationTemplatesLanguageCodeKoKR      ConversationTemplatesLanguageCode = "ko-KR"
	ConversationTemplatesLanguageCodeLoLA      ConversationTemplatesLanguageCode = "lo-LA"
	ConversationTemplatesLanguageCodeLvLV      ConversationTemplatesLanguageCode = "lv-LV"
	ConversationTemplatesLanguageCodeLtLT      ConversationTemplatesLanguageCode = "lt-LT"
	ConversationTemplatesLanguageCodeMkMK      ConversationTemplatesLanguageCode = "mk-MK"
	ConversationTemplatesLanguageCodeMsMY      ConversationTemplatesLanguageCode = "ms-MY"
	ConversationTemplatesLanguageCodeMlIN      ConversationTemplatesLanguageCode = "ml-IN"
	ConversationTemplatesLanguageCodeMtMT      ConversationTemplatesLanguageCode = "mt-MT"
	ConversationTemplatesLanguageCodeMrIN      ConversationTemplatesLanguageCode = "mr-IN"
	ConversationTemplatesLanguageCodeMnMN      ConversationTemplatesLanguageCode = "mn-MN"
	ConversationTemplatesLanguageCodeNeNP      ConversationTemplatesLanguageCode = "ne-NP"
	ConversationTemplatesLanguageCodeNbNO      ConversationTemplatesLanguageCode = "nb-NO"
	ConversationTemplatesLanguageCodeNoNO      ConversationTemplatesLanguageCode = "no-NO"
	ConversationTemplatesLanguageCodeFaIR      ConversationTemplatesLanguageCode = "fa-IR"
	ConversationTemplatesLanguageCodePlPL      ConversationTemplatesLanguageCode = "pl-PL"
	ConversationTemplatesLanguageCodePtBR      ConversationTemplatesLanguageCode = "pt-BR"
	ConversationTemplatesLanguageCodePtPT      ConversationTemplatesLanguageCode = "pt-PT"
	ConversationTemplatesLanguageCodePaGuruIN  ConversationTemplatesLanguageCode = "pa-Guru-IN"
	ConversationTemplatesLanguageCodeRoRO      ConversationTemplatesLanguageCode = "ro-RO"
	ConversationTemplatesLanguageCodeRuRU      ConversationTemplatesLanguageCode = "ru-RU"
	ConversationTemplatesLanguageCodeSrRS      ConversationTemplatesLanguageCode = "sr-RS"
	ConversationTemplatesLanguageCodeSiLK      ConversationTemplatesLanguageCode = "si-LK"
	ConversationTemplatesLanguageCodeSkSK      ConversationTemplatesLanguageCode = "sk-SK"
	ConversationTemplatesLanguageCodeSlSI      ConversationTemplatesLanguageCode = "sl-SI"
	ConversationTemplatesLanguageCodeEsAR      ConversationTemplatesLanguageCode = "es-AR"
	ConversationTemplatesLanguageCodeEsBO      ConversationTemplatesLanguageCode = "es-BO"
	ConversationTemplatesLanguageCodeEsCL      ConversationTemplatesLanguageCode = "es-CL"
	ConversationTemplatesLanguageCodeEsCO      ConversationTemplatesLanguageCode = "es-CO"
	ConversationTemplatesLanguageCodeEsCR      ConversationTemplatesLanguageCode = "es-CR"
	ConversationTemplatesLanguageCodeEsCU      ConversationTemplatesLanguageCode = "es-CU"
	ConversationTemplatesLanguageCodeEsDO      ConversationTemplatesLanguageCode = "es-DO"
	ConversationTemplatesLanguageCodeEsEC      ConversationTemplatesLanguageCode = "es-EC"
	ConversationTemplatesLanguageCodeEsSV      ConversationTemplatesLanguageCode = "es-SV"
	ConversationTemplatesLanguageCodeEsGQ      ConversationTemplatesLanguageCode = "es-GQ"
	ConversationTemplatesLanguageCodeEsGT      ConversationTemplatesLanguageCode = "es-GT"
	ConversationTemplatesLanguageCodeEsHN      ConversationTemplatesLanguageCode = "es-HN"
	ConversationTemplatesLanguageCodeEsMX      ConversationTemplatesLanguageCode = "es-MX"
	ConversationTemplatesLanguageCodeEsNI      ConversationTemplatesLanguageCode = "es-NI"
	ConversationTemplatesLanguageCodeEsPA      ConversationTemplatesLanguageCode = "es-PA"
	ConversationTemplatesLanguageCodeEsPY      ConversationTemplatesLanguageCode = "es-PY"
	ConversationTemplatesLanguageCodeEsPE      ConversationTemplatesLanguageCode = "es-PE"
	ConversationTemplatesLanguageCodeEsPR      ConversationTemplatesLanguageCode = "es-PR"
	ConversationTemplatesLanguageCodeEsES      ConversationTemplatesLanguageCode = "es-ES"
	ConversationTemplatesLanguageCodeEsUS      ConversationTemplatesLanguageCode = "es-US"
	ConversationTemplatesLanguageCodeEsUY      ConversationTemplatesLanguageCode = "es-UY"
	ConversationTemplatesLanguageCodeEsVE      ConversationTemplatesLanguageCode = "es-VE"
	ConversationTemplatesLanguageCodeSuID      ConversationTemplatesLanguageCode = "su-ID"
	ConversationTemplatesLanguageCodeSwKE      ConversationTemplatesLanguageCode = "sw-KE"
	ConversationTemplatesLanguageCodeSwTZ      ConversationTemplatesLanguageCode = "sw-TZ"
	ConversationTemplatesLanguageCodeSvSE      ConversationTemplatesLanguageCode = "sv-SE"
	ConversationTemplatesLanguageCodeTaIN      ConversationTemplatesLanguageCode = "ta-IN"
	ConversationTemplatesLanguageCodeTaMY      ConversationTemplatesLanguageCode = "ta-MY"
	ConversationTemplatesLanguageCodeTaSG      ConversationTemplatesLanguageCode = "ta-SG"
	ConversationTemplatesLanguageCodeTaLK      ConversationTemplatesLanguageCode = "ta-LK"
	ConversationTemplatesLanguageCodeTeIN      ConversationTemplatesLanguageCode = "te-IN"
	ConversationTemplatesLanguageCodeThTH      ConversationTemplatesLanguageCode = "th-TH"
	ConversationTemplatesLanguageCodeTrTR      ConversationTemplatesLanguageCode = "tr-TR"
	ConversationTemplatesLanguageCodeUkUA      ConversationTemplatesLanguageCode = "uk-UA"
	ConversationTemplatesLanguageCodeUrIN      ConversationTemplatesLanguageCode = "ur-IN"
	ConversationTemplatesLanguageCodeUrPK      ConversationTemplatesLanguageCode = "ur-PK"
	ConversationTemplatesLanguageCodeUzUZ      ConversationTemplatesLanguageCode = "uz-UZ"
	ConversationTemplatesLanguageCodeViVN      ConversationTemplatesLanguageCode = "vi-VN"
	ConversationTemplatesLanguageCodeZuZA      ConversationTemplatesLanguageCode = "zu-ZA"
)

func (e *ConversationTemplatesLanguageCode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConversationTemplatesLanguageCode(s)
	case string:
		*e = ConversationTemplatesLanguageCode(s)
	default:
		return fmt.Errorf("unsupported scan type for ConversationTemplatesLanguageCode: %T", src)
	}
	return nil
}

type NullConversationTemplatesLanguageCode struct {
	ConversationTemplatesLanguageCode ConversationTemplatesLanguageCode `json:"conversation_templates_language_code"`
	Valid                             bool                              `json:"valid"` // Valid is true if ConversationTemplatesLanguageCode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConversationTemplatesLanguageCode) Scan(value interface{}) error {
	if value == nil {
		ns.ConversationTemplatesLanguageCode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConversationTemplatesLanguageCode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConversationTemplatesLanguageCode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConversationTemplatesLanguageCode), nil
}

type IntegrationsType string

const (
	IntegrationsTypeConference     IntegrationsType = "Conference"
	IntegrationsTypeCalendar       IntegrationsType = "Calendar"
	IntegrationsTypeTaskManagement IntegrationsType = "Task Management"
	IntegrationsTypeAccount        IntegrationsType = "Account"
	IntegrationsTypeOffline        IntegrationsType = "Offline"
	IntegrationsTypeOffice         IntegrationsType = "Office"
	IntegrationsTypeCRM            IntegrationsType = "CRM"
	IntegrationsTypeChat           IntegrationsType = "Chat"
)

func (e *IntegrationsType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IntegrationsType(s)
	case string:
		*e = IntegrationsType(s)
	default:
		return fmt.Errorf("unsupported scan type for IntegrationsType: %T", src)
	}
	return nil
}

type NullIntegrationsType struct {
	IntegrationsType IntegrationsType `json:"integrations_type"`
	Valid            bool             `json:"valid"` // Valid is true if IntegrationsType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIntegrationsType) Scan(value interface{}) error {
	if value == nil {
		ns.IntegrationsType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IntegrationsType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIntegrationsType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IntegrationsType), nil
}

type TranscriptionLanguagesCode string

const (
	TranscriptionLanguagesCodeAfZA      TranscriptionLanguagesCode = "af-ZA"
	TranscriptionLanguagesCodeSqAL      TranscriptionLanguagesCode = "sq-AL"
	TranscriptionLanguagesCodeAmET      TranscriptionLanguagesCode = "am-ET"
	TranscriptionLanguagesCodeArDZ      TranscriptionLanguagesCode = "ar-DZ"
	TranscriptionLanguagesCodeArBH      TranscriptionLanguagesCode = "ar-BH"
	TranscriptionLanguagesCodeArEG      TranscriptionLanguagesCode = "ar-EG"
	TranscriptionLanguagesCodeArIQ      TranscriptionLanguagesCode = "ar-IQ"
	TranscriptionLanguagesCodeArIL      TranscriptionLanguagesCode = "ar-IL"
	TranscriptionLanguagesCodeArJO      TranscriptionLanguagesCode = "ar-JO"
	TranscriptionLanguagesCodeArKW      TranscriptionLanguagesCode = "ar-KW"
	TranscriptionLanguagesCodeArLB      TranscriptionLanguagesCode = "ar-LB"
	TranscriptionLanguagesCodeArLY      TranscriptionLanguagesCode = "ar-LY"
	TranscriptionLanguagesCodeArMA      TranscriptionLanguagesCode = "ar-MA"
	TranscriptionLanguagesCodeArOM      TranscriptionLanguagesCode = "ar-OM"
	TranscriptionLanguagesCodeArQA      TranscriptionLanguagesCode = "ar-QA"
	TranscriptionLanguagesCodeArSA      TranscriptionLanguagesCode = "ar-SA"
	TranscriptionLanguagesCodeArSY      TranscriptionLanguagesCode = "ar-SY"
	TranscriptionLanguagesCodeArPS      TranscriptionLanguagesCode = "ar-PS"
	TranscriptionLanguagesCodeArTN      TranscriptionLanguagesCode = "ar-TN"
	TranscriptionLanguagesCodeArAE      TranscriptionLanguagesCode = "ar-AE"
	TranscriptionLanguagesCodeArYE      TranscriptionLanguagesCode = "ar-YE"
	TranscriptionLanguagesCodeHyAM      TranscriptionLanguagesCode = "hy-AM"
	TranscriptionLanguagesCodeAzAZ      TranscriptionLanguagesCode = "az-AZ"
	TranscriptionLanguagesCodeEuES      TranscriptionLanguagesCode = "eu-ES"
	TranscriptionLanguagesCodeBnBD      TranscriptionLanguagesCode = "bn-BD"
	TranscriptionLanguagesCodeBnIN      TranscriptionLanguagesCode = "bn-IN"
	TranscriptionLanguagesCodeBsBA      TranscriptionLanguagesCode = "bs-BA"
	TranscriptionLanguagesCodeBgBG      TranscriptionLanguagesCode = "bg-BG"
	TranscriptionLanguagesCodeMyMM      TranscriptionLanguagesCode = "my-MM"
	TranscriptionLanguagesCodeCaES      TranscriptionLanguagesCode = "ca-ES"
	TranscriptionLanguagesCodeZhHK      TranscriptionLanguagesCode = "zh-HK"
	TranscriptionLanguagesCodeYueHantHK TranscriptionLanguagesCode = "yue-Hant-HK"
	TranscriptionLanguagesCodeZhCN      TranscriptionLanguagesCode = "zh-CN"
	TranscriptionLanguagesCodeZh        TranscriptionLanguagesCode = "zh"
	TranscriptionLanguagesCodeCmnHansCN TranscriptionLanguagesCode = "cmn-Hans-CN"
	TranscriptionLanguagesCodeZhTW      TranscriptionLanguagesCode = "zh-TW"
	TranscriptionLanguagesCodeCmnHantTW TranscriptionLanguagesCode = "cmn-Hant-TW"
	TranscriptionLanguagesCodeHrHR      TranscriptionLanguagesCode = "hr-HR"
	TranscriptionLanguagesCodeCsCZ      TranscriptionLanguagesCode = "cs-CZ"
	TranscriptionLanguagesCodeDaDK      TranscriptionLanguagesCode = "da-DK"
	TranscriptionLanguagesCodeNlBE      TranscriptionLanguagesCode = "nl-BE"
	TranscriptionLanguagesCodeNlNL      TranscriptionLanguagesCode = "nl-NL"
	TranscriptionLanguagesCodeEnAU      TranscriptionLanguagesCode = "en-AU"
	TranscriptionLanguagesCodeEnCA      TranscriptionLanguagesCode = "en-CA"
	TranscriptionLanguagesCodeEnGH      TranscriptionLanguagesCode = "en-GH"
	TranscriptionLanguagesCodeEnHK      TranscriptionLanguagesCode = "en-HK"
	TranscriptionLanguagesCodeEnIN      TranscriptionLanguagesCode = "en-IN"
	TranscriptionLanguagesCodeEnIE      TranscriptionLanguagesCode = "en-IE"
	TranscriptionLanguagesCodeEnKE      TranscriptionLanguagesCode = "en-KE"
	TranscriptionLanguagesCodeEnNZ      TranscriptionLanguagesCode = "en-NZ"
	TranscriptionLanguagesCodeEnNG      TranscriptionLanguagesCode = "en-NG"
	TranscriptionLanguagesCodeEnPK      TranscriptionLanguagesCode = "en-PK"
	TranscriptionLanguagesCodeEnPH      TranscriptionLanguagesCode = "en-PH"
	TranscriptionLanguagesCodeEnSG      TranscriptionLanguagesCode = "en-SG"
	TranscriptionLanguagesCodeEnZA      TranscriptionLanguagesCode = "en-ZA"
	TranscriptionLanguagesCodeEnTZ      TranscriptionLanguagesCode = "en-TZ"
	TranscriptionLanguagesCodeEnGB      TranscriptionLanguagesCode = "en-GB"
	TranscriptionLanguagesCodeEnUS      TranscriptionLanguagesCode = "en-US"
	TranscriptionLanguagesCodeEtEE      TranscriptionLanguagesCode = "et-EE"
	TranscriptionLanguagesCodeFilPH     TranscriptionLanguagesCode = "fil-PH"
	TranscriptionLanguagesCodeFiFI      TranscriptionLanguagesCode = "fi-FI"
	TranscriptionLanguagesCodeFrBE      TranscriptionLanguagesCode = "fr-BE"
	TranscriptionLanguagesCodeFrCA      TranscriptionLanguagesCode = "fr-CA"
	TranscriptionLanguagesCodeFrFR      TranscriptionLanguagesCode = "fr-FR"
	TranscriptionLanguagesCodeFrCH      TranscriptionLanguagesCode = "fr-CH"
	TranscriptionLanguagesCodeGlES      TranscriptionLanguagesCode = "gl-ES"
	TranscriptionLanguagesCodeKaGE      TranscriptionLanguagesCode = "ka-GE"
	TranscriptionLanguagesCodeDeAT      TranscriptionLanguagesCode = "de-AT"
	TranscriptionLanguagesCodeDeDE      TranscriptionLanguagesCode = "de-DE"
	TranscriptionLanguagesCodeDeCH      TranscriptionLanguagesCode = "de-CH"
	TranscriptionLanguagesCodeElGR      TranscriptionLanguagesCode = "el-GR"
	TranscriptionLanguagesCodeGuIN      TranscriptionLanguagesCode = "gu-IN"
	TranscriptionLanguagesCodeHeIL      TranscriptionLanguagesCode = "he-IL"
	TranscriptionLanguagesCodeIwIL      TranscriptionLanguagesCode = "iw-IL"
	TranscriptionLanguagesCodeHiIN      TranscriptionLanguagesCode = "hi-IN"
	TranscriptionLanguagesCodeHuHU      TranscriptionLanguagesCode = "hu-HU"
	TranscriptionLanguagesCodeIsIS      TranscriptionLanguagesCode = "is-IS"
	TranscriptionLanguagesCodeIDID      TranscriptionLanguagesCode = "id-ID"
	TranscriptionLanguagesCodeGaIE      TranscriptionLanguagesCode = "ga-IE"
	TranscriptionLanguagesCodeItIT      TranscriptionLanguagesCode = "it-IT"
	TranscriptionLanguagesCodeItCH      TranscriptionLanguagesCode = "it-CH"
	TranscriptionLanguagesCodeJaJP      TranscriptionLanguagesCode = "ja-JP"
	TranscriptionLanguagesCodeJvID      TranscriptionLanguagesCode = "jv-ID"
	TranscriptionLanguagesCodeKnIN      TranscriptionLanguagesCode = "kn-IN"
	TranscriptionLanguagesCodeKkKZ      TranscriptionLanguagesCode = "kk-KZ"
	TranscriptionLanguagesCodeKmKH      TranscriptionLanguagesCode = "km-KH"
	TranscriptionLanguagesCodeKoKR      TranscriptionLanguagesCode = "ko-KR"
	TranscriptionLanguagesCodeLoLA      TranscriptionLanguagesCode = "lo-LA"
	TranscriptionLanguagesCodeLvLV      TranscriptionLanguagesCode = "lv-LV"
	TranscriptionLanguagesCodeLtLT      TranscriptionLanguagesCode = "lt-LT"
	TranscriptionLanguagesCodeMkMK      TranscriptionLanguagesCode = "mk-MK"
	TranscriptionLanguagesCodeMsMY      TranscriptionLanguagesCode = "ms-MY"
	TranscriptionLanguagesCodeMlIN      TranscriptionLanguagesCode = "ml-IN"
	TranscriptionLanguagesCodeMtMT      TranscriptionLanguagesCode = "mt-MT"
	TranscriptionLanguagesCodeMrIN      TranscriptionLanguagesCode = "mr-IN"
	TranscriptionLanguagesCodeMnMN      TranscriptionLanguagesCode = "mn-MN"
	TranscriptionLanguagesCodeNeNP      TranscriptionLanguagesCode = "ne-NP"
	TranscriptionLanguagesCodeNbNO      TranscriptionLanguagesCode = "nb-NO"
	TranscriptionLanguagesCodeNoNO      TranscriptionLanguagesCode = "no-NO"
	TranscriptionLanguagesCodeFaIR      TranscriptionLanguagesCode = "fa-IR"
	TranscriptionLanguagesCodePlPL      TranscriptionLanguagesCode = "pl-PL"
	TranscriptionLanguagesCodePtBR      TranscriptionLanguagesCode = "pt-BR"
	TranscriptionLanguagesCodePtPT      TranscriptionLanguagesCode = "pt-PT"
	TranscriptionLanguagesCodePaGuruIN  TranscriptionLanguagesCode = "pa-Guru-IN"
	TranscriptionLanguagesCodeRoRO      TranscriptionLanguagesCode = "ro-RO"
	TranscriptionLanguagesCodeRuRU      TranscriptionLanguagesCode = "ru-RU"
	TranscriptionLanguagesCodeSrRS      TranscriptionLanguagesCode = "sr-RS"
	TranscriptionLanguagesCodeSiLK      TranscriptionLanguagesCode = "si-LK"
	TranscriptionLanguagesCodeSkSK      TranscriptionLanguagesCode = "sk-SK"
	TranscriptionLanguagesCodeSlSI      TranscriptionLanguagesCode = "sl-SI"
	TranscriptionLanguagesCodeEsAR      TranscriptionLanguagesCode = "es-AR"
	TranscriptionLanguagesCodeEsBO      TranscriptionLanguagesCode = "es-BO"
	TranscriptionLanguagesCodeEsCL      TranscriptionLanguagesCode = "es-CL"
	TranscriptionLanguagesCodeEsCO      TranscriptionLanguagesCode = "es-CO"
	TranscriptionLanguagesCodeEsCR      TranscriptionLanguagesCode = "es-CR"
	TranscriptionLanguagesCodeEsCU      TranscriptionLanguagesCode = "es-CU"
	TranscriptionLanguagesCodeEsDO      TranscriptionLanguagesCode = "es-DO"
	TranscriptionLanguagesCodeEsEC      TranscriptionLanguagesCode = "es-EC"
	TranscriptionLanguagesCodeEsSV      TranscriptionLanguagesCode = "es-SV"
	TranscriptionLanguagesCodeEsGQ      TranscriptionLanguagesCode = "es-GQ"
	TranscriptionLanguagesCodeEsGT      TranscriptionLanguagesCode = "es-GT"
	TranscriptionLanguagesCodeEsHN      TranscriptionLanguagesCode = "es-HN"
	TranscriptionLanguagesCodeEsMX      TranscriptionLanguagesCode = "es-MX"
	TranscriptionLanguagesCodeEsNI      TranscriptionLanguagesCode = "es-NI"
	TranscriptionLanguagesCodeEsPA      TranscriptionLanguagesCode = "es-PA"
	TranscriptionLanguagesCodeEsPY      TranscriptionLanguagesCode = "es-PY"
	TranscriptionLanguagesCodeEsPE      TranscriptionLanguagesCode = "es-PE"
	TranscriptionLanguagesCodeEsPR      TranscriptionLanguagesCode = "es-PR"
	TranscriptionLanguagesCodeEsES      TranscriptionLanguagesCode = "es-ES"
	TranscriptionLanguagesCodeEsUS      TranscriptionLanguagesCode = "es-US"
	TranscriptionLanguagesCodeEsUY      TranscriptionLanguagesCode = "es-UY"
	TranscriptionLanguagesCodeEsVE      TranscriptionLanguagesCode = "es-VE"
	TranscriptionLanguagesCodeSuID      TranscriptionLanguagesCode = "su-ID"
	TranscriptionLanguagesCodeSwKE      TranscriptionLanguagesCode = "sw-KE"
	TranscriptionLanguagesCodeSwTZ      TranscriptionLanguagesCode = "sw-TZ"
	TranscriptionLanguagesCodeSvSE      TranscriptionLanguagesCode = "sv-SE"
	TranscriptionLanguagesCodeTaIN      TranscriptionLanguagesCode = "ta-IN"
	TranscriptionLanguagesCodeTaMY      TranscriptionLanguagesCode = "ta-MY"
	TranscriptionLanguagesCodeTaSG      TranscriptionLanguagesCode = "ta-SG"
	TranscriptionLanguagesCodeTaLK      TranscriptionLanguagesCode = "ta-LK"
	TranscriptionLanguagesCodeTeIN      TranscriptionLanguagesCode = "te-IN"
	TranscriptionLanguagesCodeThTH      TranscriptionLanguagesCode = "th-TH"
	TranscriptionLanguagesCodeTrTR      TranscriptionLanguagesCode = "tr-TR"
	TranscriptionLanguagesCodeUkUA      TranscriptionLanguagesCode = "uk-UA"
	TranscriptionLanguagesCodeUrIN      TranscriptionLanguagesCode = "ur-IN"
	TranscriptionLanguagesCodeUrPK      TranscriptionLanguagesCode = "ur-PK"
	TranscriptionLanguagesCodeUzUZ      TranscriptionLanguagesCode = "uz-UZ"
	TranscriptionLanguagesCodeViVN      TranscriptionLanguagesCode = "vi-VN"
	TranscriptionLanguagesCodeZuZA      TranscriptionLanguagesCode = "zu-ZA"
)

func (e *TranscriptionLanguagesCode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TranscriptionLanguagesCode(s)
	case string:
		*e = TranscriptionLanguagesCode(s)
	default:
		return fmt.Errorf("unsupported scan type for TranscriptionLanguagesCode: %T", src)
	}
	return nil
}

type NullTranscriptionLanguagesCode struct {
	TranscriptionLanguagesCode TranscriptionLanguagesCode `json:"transcription_languages_code"`
	Valid                      bool                       `json:"valid"` // Valid is true if TranscriptionLanguagesCode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTranscriptionLanguagesCode) Scan(value interface{}) error {
	if value == nil {
		ns.TranscriptionLanguagesCode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TranscriptionLanguagesCode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTranscriptionLanguagesCode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TranscriptionLanguagesCode), nil
}

type TranscriptionLanguagesIso string

const (
	TranscriptionLanguagesIsoAf TranscriptionLanguagesIso = "af"
	TranscriptionLanguagesIsoSq TranscriptionLanguagesIso = "sq"
	TranscriptionLanguagesIsoAm TranscriptionLanguagesIso = "am"
	TranscriptionLanguagesIsoAr TranscriptionLanguagesIso = "ar"
	TranscriptionLanguagesIsoHy TranscriptionLanguagesIso = "hy"
	TranscriptionLanguagesIsoAz TranscriptionLanguagesIso = "az"
	TranscriptionLanguagesIsoEu TranscriptionLanguagesIso = "eu"
	TranscriptionLanguagesIsoBn TranscriptionLanguagesIso = "bn"
	TranscriptionLanguagesIsoBs TranscriptionLanguagesIso = "bs"
	TranscriptionLanguagesIsoBg TranscriptionLanguagesIso = "bg"
	TranscriptionLanguagesIsoMy TranscriptionLanguagesIso = "my"
	TranscriptionLanguagesIsoCa TranscriptionLanguagesIso = "ca"
	TranscriptionLanguagesIsoZh TranscriptionLanguagesIso = "zh"
	TranscriptionLanguagesIsoHr TranscriptionLanguagesIso = "hr"
	TranscriptionLanguagesIsoCs TranscriptionLanguagesIso = "cs"
	TranscriptionLanguagesIsoDa TranscriptionLanguagesIso = "da"
	TranscriptionLanguagesIsoNl TranscriptionLanguagesIso = "nl"
	TranscriptionLanguagesIsoEn TranscriptionLanguagesIso = "en"
	TranscriptionLanguagesIsoEt TranscriptionLanguagesIso = "et"
	TranscriptionLanguagesIsoTl TranscriptionLanguagesIso = "tl"
	TranscriptionLanguagesIsoFi TranscriptionLanguagesIso = "fi"
	TranscriptionLanguagesIsoFr TranscriptionLanguagesIso = "fr"
	TranscriptionLanguagesIsoGl TranscriptionLanguagesIso = "gl"
	TranscriptionLanguagesIsoKa TranscriptionLanguagesIso = "ka"
	TranscriptionLanguagesIsoDe TranscriptionLanguagesIso = "de"
	TranscriptionLanguagesIsoEl TranscriptionLanguagesIso = "el"
	TranscriptionLanguagesIsoGu TranscriptionLanguagesIso = "gu"
	TranscriptionLanguagesIsoHe TranscriptionLanguagesIso = "he"
	TranscriptionLanguagesIsoHi TranscriptionLanguagesIso = "hi"
	TranscriptionLanguagesIsoHu TranscriptionLanguagesIso = "hu"
	TranscriptionLanguagesIsoIs TranscriptionLanguagesIso = "is"
	TranscriptionLanguagesIsoID TranscriptionLanguagesIso = "id"
	TranscriptionLanguagesIsoIt TranscriptionLanguagesIso = "it"
	TranscriptionLanguagesIsoJa TranscriptionLanguagesIso = "ja"
	TranscriptionLanguagesIsoJv TranscriptionLanguagesIso = "jv"
	TranscriptionLanguagesIsoKn TranscriptionLanguagesIso = "kn"
	TranscriptionLanguagesIsoKk TranscriptionLanguagesIso = "kk"
	TranscriptionLanguagesIsoKm TranscriptionLanguagesIso = "km"
	TranscriptionLanguagesIsoKo TranscriptionLanguagesIso = "ko"
	TranscriptionLanguagesIsoLo TranscriptionLanguagesIso = "lo"
	TranscriptionLanguagesIsoLv TranscriptionLanguagesIso = "lv"
	TranscriptionLanguagesIsoLt TranscriptionLanguagesIso = "lt"
	TranscriptionLanguagesIsoMk TranscriptionLanguagesIso = "mk"
	TranscriptionLanguagesIsoMs TranscriptionLanguagesIso = "ms"
	TranscriptionLanguagesIsoMl TranscriptionLanguagesIso = "ml"
	TranscriptionLanguagesIsoMt TranscriptionLanguagesIso = "mt"
	TranscriptionLanguagesIsoMr TranscriptionLanguagesIso = "mr"
	TranscriptionLanguagesIsoMn TranscriptionLanguagesIso = "mn"
	TranscriptionLanguagesIsoNe TranscriptionLanguagesIso = "ne"
	TranscriptionLanguagesIsoNo TranscriptionLanguagesIso = "no"
	TranscriptionLanguagesIsoFa TranscriptionLanguagesIso = "fa"
	TranscriptionLanguagesIsoPl TranscriptionLanguagesIso = "pl"
	TranscriptionLanguagesIsoPt TranscriptionLanguagesIso = "pt"
	TranscriptionLanguagesIsoPa TranscriptionLanguagesIso = "pa"
	TranscriptionLanguagesIsoRo TranscriptionLanguagesIso = "ro"
	TranscriptionLanguagesIsoRu TranscriptionLanguagesIso = "ru"
	TranscriptionLanguagesIsoSr TranscriptionLanguagesIso = "sr"
	TranscriptionLanguagesIsoSi TranscriptionLanguagesIso = "si"
	TranscriptionLanguagesIsoSk TranscriptionLanguagesIso = "sk"
	TranscriptionLanguagesIsoSl TranscriptionLanguagesIso = "sl"
	TranscriptionLanguagesIsoEs TranscriptionLanguagesIso = "es"
	TranscriptionLanguagesIsoSu TranscriptionLanguagesIso = "su"
	TranscriptionLanguagesIsoSw TranscriptionLanguagesIso = "sw"
	TranscriptionLanguagesIsoSv TranscriptionLanguagesIso = "sv"
	TranscriptionLanguagesIsoTa TranscriptionLanguagesIso = "ta"
	TranscriptionLanguagesIsoTe TranscriptionLanguagesIso = "te"
	TranscriptionLanguagesIsoTh TranscriptionLanguagesIso = "th"
	TranscriptionLanguagesIsoTr TranscriptionLanguagesIso = "tr"
	TranscriptionLanguagesIsoUk TranscriptionLanguagesIso = "uk"
	TranscriptionLanguagesIsoUr TranscriptionLanguagesIso = "ur"
	TranscriptionLanguagesIsoUz TranscriptionLanguagesIso = "uz"
	TranscriptionLanguagesIsoVi TranscriptionLanguagesIso = "vi"
	TranscriptionLanguagesIsoZu TranscriptionLanguagesIso = "zu"
)

func (e *TranscriptionLanguagesIso) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TranscriptionLanguagesIso(s)
	case string:
		*e = TranscriptionLanguagesIso(s)
	default:
		return fmt.Errorf("unsupported scan type for TranscriptionLanguagesIso: %T", src)
	}
	return nil
}

type NullTranscriptionLanguagesIso struct {
	TranscriptionLanguagesIso TranscriptionLanguagesIso `json:"transcription_languages_iso"`
	Valid                     bool                      `json:"valid"` // Valid is true if TranscriptionLanguagesIso is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTranscriptionLanguagesIso) Scan(value interface{}) error {
	if value == nil {
		ns.TranscriptionLanguagesIso, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TranscriptionLanguagesIso.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTranscriptionLanguagesIso) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TranscriptionLanguagesIso), nil
}

type ConversationTemplate struct {
	ID           uint32                            `json:"id"`
	Name         string                            `json:"name"`
	UserID       uint32                            `json:"user_id"`
	UserUuid     string                            `json:"user_uuid"`
	CategoryID   uint32                            `json:"category_id"`
	LanguageCode ConversationTemplatesLanguageCode `json:"language_code"`
	Summary      sql.NullString                    `json:"summary"`
	Description  sql.NullString                    `json:"description"`
	Agenda       sql.NullString                    `json:"agenda"`
	Dictionary   sql.NullString                    `json:"dictionary"`
	Sections     json.RawMessage                   `json:"sections"`
	CreatedAt    time.Time                         `json:"created_at"`
	UpdatedAt    sql.NullTime                      `json:"updated_at"`
}

type Integration struct {
	ID              uint64           `json:"id"`
	UpdatedAt       sql.NullTime     `json:"updated_at"`
	UserUuid        string           `json:"user_uuid"`
	Type            IntegrationsType `json:"type"`
	Vendor          string           `json:"vendor"`
	Product         sql.NullString   `json:"product"`
	Provider        string           `json:"provider"`
	Url             sql.NullString   `json:"url"`
	NextSyncToken   sql.NullString   `json:"next_sync_token"`
	WatchToken      sql.NullString   `json:"watch_token"`
	WatchExpiration sql.NullString   `json:"watch_expiration"`
	Usertype        sql.NullInt32    `json:"usertype"`
	Active          sql.NullBool     `json:"active"`
	ErrorCode       sql.NullString   `json:"error_code"`
	ErrorMessage    sql.NullString   `json:"error_message"`
	CreatedAt       sql.NullTime     `json:"created_at"`
}

type TranscriptionLanguage struct {
	ID                                  uint64                     `json:"id"`
	Iso                                 TranscriptionLanguagesIso  `json:"iso"`
	Code                                TranscriptionLanguagesCode `json:"code"`
	Value                               string                     `json:"value"`
	Country                             string                     `json:"country"`
	Language                            string                     `json:"language"`
	Model                               string                     `json:"model"`
	AlignModel                          sql.NullString             `json:"align_model"`
	Stemmer                             sql.NullString             `json:"stemmer"`
	Stop                                sql.NullString             `json:"stop"`
	Google                              bool                       `json:"google"`
	Microsoft                           bool                       `json:"microsoft"`
	Whisper                             bool                       `json:"whisper"`
	Available                           bool                       `json:"available"`
	Punctuation                         bool                       `json:"punctuation"`
	Speakers                            bool                       `json:"speakers"`
	Boost                               bool                       `json:"boost"`
	Confidence                          bool                       `json:"confidence"`
	Profanity                           bool                       `json:"profanity"`
	Phrase                              bool                       `json:"phrase"`
	Identification                      bool                       `json:"identification"`
	BoostMeetingAssistant               sql.NullString             `json:"boost_meeting_assistant"`
	BoostMeetingTitle                   sql.NullString             `json:"boost_meeting_title"`
	BoostMeetingParticipants            sql.NullString             `json:"boost_meeting_participants"`
	BoostMeetingParticipantsActual      sql.NullString             `json:"boost_meeting_participants_actual"`
	BoostTemplateCustomWords            sql.NullString             `json:"boost_template_custom_words"`
	BoostTemplateKeywordBasedHighlights sql.NullString             `json:"boost_template_keyword_based_highlights"`
}

type User struct {
	ID                uint32         `json:"id"`
	Name              string         `json:"name"`
	FirstName         sql.NullString `json:"first_name"`
	LastName          sql.NullString `json:"last_name"`
	CompanyID         sql.NullInt32  `json:"company_id"`
	Birthday          sql.NullString `json:"birthday"`
	Photo             sql.NullString `json:"photo"`
	Phone             sql.NullString `json:"phone"`
	Email             string         `json:"email"`
	Token             sql.NullString `json:"token"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
	DeletedAt         sql.NullTime   `json:"deleted_at"`
	Cleaned           bool           `json:"cleaned"`
	DisabledAt        sql.NullTime   `json:"disabled_at"`
	StripeID          sql.NullString `json:"stripe_id"`
	PmType            sql.NullString `json:"pm_type"`
	PmLastFour        sql.NullString `json:"pm_last_four"`
	TrialEndsAt       sql.NullTime   `json:"trial_ends_at"`
	HadPaidTrial      bool           `json:"had_paid_trial"`
	Expiresin         sql.NullInt32  `json:"expiresin"`
	Refreshtoken      sql.NullString `json:"refreshtoken"`
	Updatedat         sql.NullTime   `json:"updatedat"`
	LastLogin         sql.NullTime   `json:"last_login"`
	LastActivity      sql.NullInt32  `json:"last_activity"`
	EmailVerifiedAt   sql.NullTime   `json:"email_verified_at"`
	Sub               string         `json:"sub"`
	Uuid              string         `json:"uuid"`
	RememberToken     sql.NullString `json:"remember_token"`
	Role              sql.NullString `json:"role"`
	HearAboutUs       sql.NullString `json:"hear_about_us"`
	DefaultRegionCode sql.NullString `json:"default_region_code"`
}
