// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transcription_languages_queries.sql

package models

import (
	"context"
	"database/sql"
)

const getAvailableTranscriptionLanguages = `-- name: GetAvailableTranscriptionLanguages :many
SELECT
    tl.id,
    tl.code,
    tl.value,
    tl.country,
    tl.language,
    tl.boost_meeting_assistant,
    tl.boost_meeting_title,
    tl.boost_meeting_participants,
    tl.boost_meeting_participants_actual,
    tl.boost_template_custom_words,
    tl.boost_template_keyword_based_highlights
FROM
    transcription_languages tl
WHERE
    tl.available = 1
`

type GetAvailableTranscriptionLanguagesRow struct {
	ID                                  uint64                     `json:"id"`
	Code                                TranscriptionLanguagesCode `json:"code"`
	Value                               string                     `json:"value"`
	Country                             string                     `json:"country"`
	Language                            string                     `json:"language"`
	BoostMeetingAssistant               sql.NullString             `json:"boost_meeting_assistant"`
	BoostMeetingTitle                   sql.NullString             `json:"boost_meeting_title"`
	BoostMeetingParticipants            sql.NullString             `json:"boost_meeting_participants"`
	BoostMeetingParticipantsActual      sql.NullString             `json:"boost_meeting_participants_actual"`
	BoostTemplateCustomWords            sql.NullString             `json:"boost_template_custom_words"`
	BoostTemplateKeywordBasedHighlights sql.NullString             `json:"boost_template_keyword_based_highlights"`
}

func (q *Queries) GetAvailableTranscriptionLanguages(ctx context.Context) ([]GetAvailableTranscriptionLanguagesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAvailableTranscriptionLanguages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAvailableTranscriptionLanguagesRow
	for rows.Next() {
		var i GetAvailableTranscriptionLanguagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Value,
			&i.Country,
			&i.Language,
			&i.BoostMeetingAssistant,
			&i.BoostMeetingTitle,
			&i.BoostMeetingParticipants,
			&i.BoostMeetingParticipantsActual,
			&i.BoostTemplateCustomWords,
			&i.BoostTemplateKeywordBasedHighlights,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
