// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_queries.sql

package models

import (
	"context"
)

const getUserForUpcomingMeetings = `-- name: GetUserForUpcomingMeetings :one
SELECT
    u.uuid,
    u.name,
    u.email
FROM
    users u
WHERE
    u.id = ?
    AND u.deleted_at IS NULL
`

type GetUserForUpcomingMeetingsRow struct {
	Uuid  string `json:"uuid"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (q *Queries) GetUserForUpcomingMeetings(ctx context.Context, id uint32) (GetUserForUpcomingMeetingsRow, error) {
	row := q.db.QueryRowContext(ctx, getUserForUpcomingMeetings, id)
	var i GetUserForUpcomingMeetingsRow
	err := row.Scan(&i.Uuid, &i.Name, &i.Email)
	return i, err
}
