// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_queries.sql

package models

import (
	"context"
)

const getUserForUpcomingMeetings = `-- name: GetUserForUpcomingMeetings :one
SELECT
    u.id,
    u.name,
    u.email
FROM
    users u
WHERE
    u.uuid = ?
    AND u.deleted_at IS NULL
`

type GetUserForUpcomingMeetingsRow struct {
	ID    uint32 `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (q *Queries) GetUserForUpcomingMeetings(ctx context.Context, uuid string) (GetUserForUpcomingMeetingsRow, error) {
	row := q.db.QueryRowContext(ctx, getUserForUpcomingMeetings, uuid)
	var i GetUserForUpcomingMeetingsRow
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}
