CREATE TABLE `users` (
    `id` int unsigned NOT NULL AUTO_INCREMENT,
    `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    `first_name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `last_name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `company_id` int DEFAULT NULL,
    `birthday` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `photo` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `phone` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `email` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    `token` varchar(7515) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NULL DEFAULT NULL,
    `deleted_at` timestamp NULL DEFAULT NULL,
    `cleaned` tinyint(1) NOT NULL DEFAULT '0',
    `disabled_at` timestamp NULL DEFAULT NULL,
    `stripe_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `pm_type` varchar(56) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `pm_last_four` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `trial_ends_at` timestamp NULL DEFAULT NULL,
    `had_paid_trial` tinyint(1) NOT NULL DEFAULT '0',
    `expiresIn` int DEFAULT NULL,
    `refreshToken` varchar(4096) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `updatedAt` timestamp NULL DEFAULT NULL,
    `last_login` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    `last_activity` int DEFAULT NULL,
    `email_verified_at` timestamp NULL DEFAULT NULL,
    `sub` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    `uuid` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
    `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `role` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `hear_about_us` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `default_region_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'eu',
    PRIMARY KEY (`id`) USING BTREE,
    UNIQUE KEY `users_email_unique` (`email`) USING BTREE,
    UNIQUE KEY `users_sub_unique` (`sub`) USING BTREE,
    UNIQUE KEY `uuid` (`uuid`),
    KEY `users_stripe_id_index` (`stripe_id`) USING BTREE,
    KEY `users_company_id_index` (`company_id`),
    KEY `users_trial_ends_at` (`trial_ends_at`) USING BTREE,
    KEY `users_deleted_at` (`deleted_at`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `transcription_languages` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `iso` enum('af','sq','am','ar','hy','az','eu','bn','bs','bg','my','ca','zh','hr','cs','da','nl','en','et','tl','fi','fr','gl','ka','de','el','gu','he','hi','hu','is','id','it','ja','jv','kn','kk','km','ko','lo','lv','lt','mk','ms','ml','mt','mr','mn','ne','no','fa','pl','pt','pa','ro','ru','sr','si','sk','sl','es','su','sw','sv','ta','te','th','tr','uk','ur','uz','vi','zu') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `code` enum('af-ZA','sq-AL','am-ET','ar-DZ','ar-BH','ar-EG','ar-IQ','ar-IL','ar-JO','ar-KW','ar-LB','ar-LY','ar-MA','ar-OM','ar-QA','ar-SA','ar-SY','ar-PS','ar-TN','ar-AE','ar-YE','hy-AM','az-AZ','eu-ES','bn-BD','bn-IN','bs-BA','bg-BG','my-MM','ca-ES','zh-HK','yue-Hant-HK','zh-CN','zh','cmn-Hans-CN','zh-TW','cmn-Hant-TW','hr-HR','cs-CZ','da-DK','nl-BE','nl-NL','en-AU','en-CA','en-GH','en-HK','en-IN','en-IE','en-KE','en-NZ','en-NG','en-PK','en-PH','en-SG','en-ZA','en-TZ','en-GB','en-US','et-EE','fil-PH','fi-FI','fr-BE','fr-CA','fr-FR','fr-CH','gl-ES','ka-GE','de-AT','de-DE','de-CH','el-GR','gu-IN','he-IL','iw-IL','hi-IN','hu-HU','is-IS','id-ID','ga-IE','it-IT','it-CH','ja-JP','jv-ID','kn-IN','kk-KZ','km-KH','ko-KR','lo-LA','lv-LV','lt-LT','mk-MK','ms-MY','ml-IN','mt-MT','mr-IN','mn-MN','ne-NP','nb-NO','no-NO','fa-IR','pl-PL','pt-BR','pt-PT','pa-Guru-IN','ro-RO','ru-RU','sr-RS','si-LK','sk-SK','sl-SI','es-AR','es-BO','es-CL','es-CO','es-CR','es-CU','es-DO','es-EC','es-SV','es-GQ','es-GT','es-HN','es-MX','es-NI','es-PA','es-PY','es-PE','es-PR','es-ES','es-US','es-UY','es-VE','su-ID','sw-KE','sw-TZ','sv-SE','ta-IN','ta-MY','ta-SG','ta-LK','te-IN','th-TH','tr-TR','uk-UA','ur-IN','ur-PK','uz-UZ','vi-VN','zu-ZA') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `value` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `country` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `language` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `model` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `align_model` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `stemmer` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `stop` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `google` tinyint(1) NOT NULL DEFAULT '0',
  `microsoft` tinyint(1) NOT NULL DEFAULT '0',
  `whisper` tinyint(1) NOT NULL DEFAULT '0',
  `available` tinyint(1) NOT NULL DEFAULT '0',
  `punctuation` tinyint(1) NOT NULL DEFAULT '0',
  `speakers` tinyint(1) NOT NULL DEFAULT '0',
  `boost` tinyint(1) NOT NULL DEFAULT '0',
  `confidence` tinyint(1) NOT NULL DEFAULT '0',
  `profanity` tinyint(1) NOT NULL DEFAULT '0',
  `phrase` tinyint(1) NOT NULL DEFAULT '0',
  `identification` tinyint(1) NOT NULL DEFAULT '0',
  `boost_meeting_assistant` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `boost_meeting_title` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `boost_meeting_participants` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `boost_meeting_participants_actual` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `boost_template_custom_words` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `boost_template_keyword_based_highlights` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`),
  KEY `value` (`value`,`google`,`microsoft`,`whisper`,`available`,`model`,`align_model`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `conversation_templates` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_id` int unsigned NOT NULL,
  `user_uuid` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `category_id` int unsigned NOT NULL,
  `language_code` enum('af-ZA','sq-AL','am-ET','ar-DZ','ar-BH','ar-EG','ar-IQ','ar-IL','ar-JO','ar-KW','ar-LB','ar-LY','ar-MA','ar-OM','ar-QA','ar-SA','ar-SY','ar-PS','ar-TN','ar-AE','ar-YE','hy-AM','az-AZ','eu-ES','bn-BD','bn-IN','bs-BA','bg-BG','my-MM','ca-ES','zh-HK','yue-Hant-HK','zh-CN','zh','cmn-Hans-CN','zh-TW','cmn-Hant-TW','hr-HR','cs-CZ','da-DK','nl-BE','nl-NL','en-AU','en-CA','en-GH','en-HK','en-IN','en-IE','en-KE','en-NZ','en-NG','en-PK','en-PH','en-SG','en-ZA','en-TZ','en-GB','en-US','et-EE','fil-PH','fi-FI','fr-BE','fr-CA','fr-FR','fr-CH','gl-ES','ka-GE','de-AT','de-DE','de-CH','el-GR','gu-IN','he-IL','iw-IL','hi-IN','hu-HU','is-IS','id-ID','ga-IE','it-IT','it-CH','ja-JP','jv-ID','kn-IN','kk-KZ','km-KH','ko-KR','lo-LA','lv-LV','lt-LT','mk-MK','ms-MY','ml-IN','mt-MT','mr-IN','mn-MN','ne-NP','nb-NO','no-NO','fa-IR','pl-PL','pt-BR','pt-PT','pa-Guru-IN','ro-RO','ru-RU','sr-RS','si-LK','sk-SK','sl-SI','es-AR','es-BO','es-CL','es-CO','es-CR','es-CU','es-DO','es-EC','es-SV','es-GQ','es-GT','es-HN','es-MX','es-NI','es-PA','es-PY','es-PE','es-PR','es-ES','es-US','es-UY','es-VE','su-ID','sw-KE','sw-TZ','sv-SE','ta-IN','ta-MY','ta-SG','ta-LK','te-IN','th-TH','tr-TR','uk-UA','ur-IN','ur-PK','uz-UZ','vi-VN','zu-ZA') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'en-US',
  `summary` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `description` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `agenda` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `dictionary` varchar(4096) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sections` json NOT NULL DEFAULT (json_array()),
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_id_name_language_code` (`user_id`,`name`,`language_code`),
  UNIQUE KEY `user_uuid_name_language_code` (`user_uuid`,`name`,`language_code`),
  KEY `ct_name` (`name`),
  KEY `FK_ct_ctc_category_id` (`category_id`) USING BTREE,
  CONSTRAINT `FK_ct_u_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_ct_u_user_uuid` FOREIGN KEY (`user_uuid`) REFERENCES `users` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `integrations` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `updated_at` timestamp NULL DEFAULT NULL,
  `user_uuid` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `type` enum('Conference','Calendar','Task Management','Account','Offline','Office','CRM','Chat') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `vendor` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `product` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `provider` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `next_sync_token` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `watch_token` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `watch_expiration` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `usertype` int DEFAULT NULL,
  `active` tinyint(1) DEFAULT '1',
  `error_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `error_message` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `vendor_idx` (`vendor`) USING BTREE,
  KEY `provider_idx` (`provider`) USING BTREE,
  KEY `user_uuid_idx` (`user_uuid`) USING BTREE,
  KEY `fk_integrations_vendor_product` (`vendor`,`product`),
  KEY `idx_integrations_product` (`product`)
) ENGINE=InnoDB AUTO_INCREMENT=4819 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

